#!/bin/sh

#-------------------------------------------------------------------
# Clean files

echo "Cleaning lfsHost-build files from /mnt/lfs..."

rm /mnt/lfs/README.md
rm -rf /mnt/lfs/jhalfs
rm -rf /mnt/lfs/sources/
rm -rf /mnt/lfs/var/lib/jhalfs
rm -rf /mnt/lfs/home/builder/blfs_root
rm -rf /mnt/lfs/home/blfs-builder/blfs_root
rm -rf /mnt/lfs/root/blfs_base1
rm /mnt/lfs/root/lfschroot.sh

echo "Truncating /mnt/lfs log files..."
find /mnt/lfs/var/log -type f -iname '*.log' -print0 | xargs -0 truncate -s0

echo "Done."

# END script
#-------------------------------------------------------------------
